/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basics;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Random;

public class App {
    public static void main(String[] args) {
        //  ............... pluralize test
        int dogCount = 1;
        System.out.println("I own " + dogCount + " " + pluralize("dog", dogCount) + ".");

        int catCount = 2;
        System.out.println("I own " + catCount + " " + pluralize("cat", catCount) + ".");

        int turtleCount = 0;
        System.out.println("I own " + turtleCount + " " + pluralize("turtle", turtleCount) + ".");
//
//       //  .............. flipNHeads test
         flipNHeads(2);

        //  .............. clock  test
          clock();
    }
//    .................................................. pluralize function
  public static String pluralize(String word, int number){
        if( number == 1){
            return word;
        }
    return word + 's';
    }

//    ..............................................flipNHeads function
    public static void flipNHeads(int n){
        byte countHead = 0;
        byte rounds = 0;

        while(countHead != n){
            Random rnd = new Random();
            double randomNumber = rnd.nextDouble();
            if(randomNumber >= 0.5){
                countHead +=1;
                System.out.println("head");
            }else if(randomNumber < 0.5 ){
                countHead = 0;
                System.out.println("tail");
            }
            rounds++;
        }
        System.out.println("It took " + rounds + " flips to flip " + countHead +" heads in a row.");
    }

//...................... time function
    public static void clock(){
        int hour;
        int minute;
        int second;
        int secondChecker = 0;
        while (true){
            LocalDateTime now = LocalDateTime.now();
            hour = now.getHour();
            minute = now.getMinute();
            second = now.getSecond();

            if(secondChecker != second){
                secondChecker = second;
                String time = now.format(DateTimeFormatter.ofPattern("HH:mm:ss"));
                System.out.println(time);
            }
        }
    }
}
